[font]
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Italic" }
size = 11
